import { Helmet } from 'react-helmet-async';
import { useEffect, useState } from 'react';
import { Container, Card, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Button, Box, TextField, CircularProgress, Select, MenuItem, FormControl, InputLabel, Chip, Grid,
} from '@mui/material';
import { Iconify } from 'src/components/iconify';
import { equipamentosService } from 'src/services';
import { EquipamentoDTO } from 'src/types';
import { useAppToast } from 'src/hooks/ToastProvider'; export default function EquipamentosView() { const toast = useAppToast(); const [equipamentos, setEquipamentos] = useState<EquipamentoDTO[]>([]); const [loading, setLoading] = useState(true); const [searchTerm, setSearchTerm] = useState(''); const [filtroStatus, setFiltroStatus] = useState(''); useEffect(() => { fetchEquipamentos(); }, []); const fetchEquipamentos = async () => { try { setLoading(true); const data = await equipamentosService.listar(); setEquipamentos(data); } catch (error) { toast.showError(error.response?.data?.message || 'Erro ao carregar equipamentos'); } finally { setLoading(false); } }; const handleSearch = async () => { if (!searchTerm.trim()) { fetchEquipamentos(); return; } try { setLoading(true); const data = await equipamentosService.buscarPorPatrimonio(searchTerm); setEquipamentos([data]); } catch (error) { toast.showError(error.response?.data?.message || 'Equipamento não encontrado'); setEquipamentos([]); } finally { setLoading(false); } }; const handleFiltroStatus = async (status) => { setFiltroStatus(status); if (!status) { fetchEquipamentos(); return; } try { setLoading(true); const data = await equipamentosService.buscarPorStatus(status); setEquipamentos(data); } catch (error) { toast.showError(error.response?.data?.message || 'Erro ao filtrar equipamentos'); } finally { setLoading(false); } }; const emUso = equipamentos.filter((e) => e.status === 'EM_USO').length; const disponiveis = equipamentos.filter((e) => e.status === 'DISPONIVEL').length; const deficientes = equipamentos.filter((e) => e.status === 'DEFICIENTE').length; return ( Equipamentos | Ticomia Financeiro</title> Equipamentos</h1> Total {/* Cards resumidos */} handleFiltroStatus('EM_USO')}> Em Uso</p> {emUso} handleFiltroStatus('DISPONIVEL')}> Disponíveis</p> {disponiveis} handleFiltroStatus('DEFICIENTE')}> Deficientes</p> {deficientes} {/* Filtros */} setSearchTerm(e.target.value)} onKeyPress={(e) => e.key === 'Enter' && handleSearch()} sx={{ minWidth200 }} /> Buscar { setSearchTerm(''); setFiltroStatus(''); fetchEquipamentos(); }} > Limpar {filtroStatus && ( handleFiltroStatus('')} /> )} {/* Tabela */} {loading ? () ( Patrimônio</TableCell> Tipo</TableCell> Vendedor</TableCell> Cidade</TableCell> Serial</TableCell> Status</TableCell> Observações</TableCell> {equipamentos.map((equipamento) => ( {equipamento.patrimonio} {equipamento.tipoEquipamento} {equipamento.vendedor || '-'} {equipamento.cidade || '-'} {equipamento.serial || '-'} {equipamento.observacoes || '-'} ))} )} );
}
