import { Helmet } from 'react-helmet-async';
import { useEffect, useState } from 'react';
import { Container, Card, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Button, Box, TextField, CircularProgress, Dialog, DialogTitle, DialogContent, DialogActions, Grid, Select, MenuItem, FormControl, InputLabel, Chip, IconButton,
} from '@mui/material';
import { Iconify } from 'src/components/iconify';
import { contasService } from 'src/services';
import { ContaBancariaDTO, ContaBancariaCreateDTO } from 'src/types';
import { useAppToast } from 'src/hooks/ToastProvider';
import { fCurrency } from 'src/utils/format-number'; const TIPOS_CONTA = [ { value'CORRENTE', label'Corrente' }, { value'POUPANCA', label'Poupança' }, { value'DIGITAL', label'Digital' }, { value'INVESTIMENTO', label'Investimento' },
]; export default function ContasView() { const toast = useAppToast(); const [contas, setContas] = useState<ContaBancariaDTO[]>([]); const [loading, setLoading] = useState(true); const [openDialog, setOpenDialog] = useState(false); const [editingId, setEditingId] = useState(null); const [formData, setFormData] = useState({ bancoId1, nome'', tipo'CORRENTE', }); useEffect(() => { fetchContas(); }, []); const fetchContas = async () => { try { setLoading(true); const data = await contasService.listar(); setContas(data); } catch (error) { toast.showError(error.response?.data?.message || 'Erro ao carregar contas'); } finally { setLoading(false); } }; const handleOpenDialog = (conta?) => { if (conta) { setEditingId(conta.id); setFormData({ bancoId, nome, tipo, agencia || '', numeroConta || '', digito || '', }); } else { setEditingId(null); setFormData({ bancoId1, nome'', tipo'CORRENTE', }); } setOpenDialog(true); }; const handleCloseDialog = () => { setOpenDialog(false); setEditingId(null); }; const handleSave = async () => { if (!formData.nome.trim()) { toast.showWarning('Nome da conta é obrigatório'); return; } try { if (editingId) { await contasService.atualizar(editingId, formData); toast.showSuccess('Conta atualizada com sucesso!'); } else { await contasService.criar(formData); toast.showSuccess('Conta criada com sucesso!'); } handleCloseDialog(); fetchContas(); } catch (error) { toast.showError(error.response?.data?.message || 'Erro ao salvar conta'); } }; const handleDelete = async (id) => { if (!confirm('Tem certeza que deseja deletar esta conta?')) return; try { await contasService.deletar(id); toast.showSuccess('Conta deletada com sucesso!'); fetchContas(); } catch (error) { toast.showError(error.response?.data?.message || 'Erro ao deletar conta'); } }; const totalSaldo = contas.reduce((sum, c) => sum + c.saldoAtual, 0); return ( Contas Bancárias | Ticomia Financeiro</title> Contas Bancárias</h1> Saldo Total onClick={() => handleOpenDialog()} > Nova Conta {/* Tabela */} {loading ? () ( Nome</TableCell> Banco</TableCell> Tipo</TableCell> Agência</TableCell> Conta</TableCell> Saldo</TableCell> Principal</TableCell> Ações</TableCell> {contas.map((conta) => ( {conta.nome} {conta.bancoNome} {conta.tipo} {conta.agencia || '-'} {conta.numeroConta ? `${conta.numeroConta}-${conta.digito}` '-'} {fCurrency(conta.saldoAtual)} {conta.principal && } handleOpenDialog(conta)} title="Editar" > handleDelete(conta.id)} title="Deletar" sx={{ color'error.main' }} > ))} )} {/* Dialog */} {editingId ? 'Editar Conta' 'Nova Conta'} setFormData({ ...formData, nome })} /> Tipo</InputLabel> setFormData({ ...formData, tipo })} > {TIPOS_CONTA.map((tipo) => ( {tipo.label} ))} setFormData({ ...formData, agencia })} /> setFormData({ ...formData, numeroConta })} /> setFormData({ ...formData, digito })} /> Cancelar</Button> Salvar );
}
