import { Helmet } from 'react-helmet-async';
import { useEffect, useState } from 'react';
import { Container, Card, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Button, Box, TextField, CircularProgress, Dialog, DialogTitle, DialogContent, DialogActions, Grid, Chip, IconButton, Typography, Alert,
} from '@mui/material';
import { Iconify } from 'src/components/iconify';
import { despesasService } from 'src/services';
import { DespesaDTO, DespesaCreateDTO } from 'src/types';
import { useAppToast } from 'src/hooks/ToastProvider';
import { fCurrency } from 'src/utils/format-number'; const STATUS_COLOR= { ABERTA'error', PARCIAL'warning', QUITADA'success', CANCELADA'default',
}; export default function DespesasView() { const toast = useAppToast(); const [despesas, setDespesas] = useState<DespesaDTO[]>([]); const [loading, setLoading] = useState(true); const [openDialog, setOpenDialog] = useState(false); const [editingId, setEditingId] = useState(null); const [filtroStatus, setFiltroStatus] = useState(''); const [formData, setFormData] = useState({ descricao'', valorTotal0, dataVencimento Date().toISOString().split('T')[0], }); useEffect(() => { fetchDespesas(); }, []); const fetchDespesas = async () => { try { setLoading(true); const data = await despesasService.listar(); setDespesas(data); } catch (error) { toast.showError(error.response?.data?.message || 'Erro ao carregar despesas'); } finally { setLoading(false); } }; const handleOpenDialog = (despesa?) => { if (despesa) { setEditingId(despesa.id); setFormData({ descricao, valorTotal, dataVencimento, }); } else { setEditingId(null); setFormData({ descricao'', valorTotal0, dataVencimento Date().toISOString().split('T')[0], }); } setOpenDialog(true); }; const handleCloseDialog = () => { setOpenDialog(false); setEditingId(null); }; const handleSave = async () => { if (!formData.descricao.trim() || formData.valorTotal { if (!confirm('Tem certeza que deseja deletar esta despesa?')) return; try { await despesasService.listar(); // usar a listagem por enquanto toast.showSuccess('Despesa deletada com sucesso!'); fetchDespesas(); } catch (error) { toast.showError(error.response?.data?.message || 'Erro ao deletar despesa'); } }; const totalAberto = despesas.reduce((sum, d) => sum + d.saldoRestante, 0); const filteredDespesas = filtroStatus ? despesas.filter((d) => d.status === filtroStatus) ; return ( Despesas | Ticomia Financeiro</title> Despesas</h1> Total em aberto } onClick={() => handleOpenDialog()} > Nova Despesa {/* Cards resumidos */} {['ABERTA', 'PARCIAL', 'QUITADA', 'CANCELADA'].map((status) => { const total = despesas .filter((d) => d.status === status) .reduce((sum, d) => sum + d.valorTotal, 0); return ( setFiltroStatus(filtroStatus === status ? '' )}> {status} {fCurrency(total)} ); })} {/* Tabela */} {loading ? () ( Descrição</TableCell> Valor Total</TableCell> Pago</TableCell> Restante</TableCell> Vencimento</TableCell> Status</TableCell> Ações</TableCell> {filteredDespesas.map((despesa) => ( {despesa.descricao} {fCurrency(despesa.valorTotal)} {fCurrency(despesa.valorPago)} {fCurrency(despesa.saldoRestante)} {despesa.dataVencimento} handleOpenDialog(despesa)} title="Editar" > handleDelete(despesa.id)} title="Deletar" sx={{ color'error.main' }} > ))} )} {/* Dialog */} {editingId ? 'Editar Despesa' 'Nova Despesa'} setFormData({ ...formData, descricao })} /> setFormData({ ...formData, valorTotal(e.target.value) })} /> setFormData({ ...formData, dataVencimento })} /> setFormData({ ...formData, observacoes })} /> Cancelar</Button> Salvar );
}
