import { Helmet } from 'react-helmet-async';
import { useEffect, useState } from 'react';
import { Container, Grid, Card, CardContent, Typography, Box, CircularProgress, Alert, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Chip,
} from '@mui/material';
import { Iconify } from 'src/components/iconify';
import { Chart } from 'src/components/chart';
import { dashboardService, agendaService } from 'src/services';
import { DashboardCompletoDTO, TopVendedorDTO, AlertaPagamentoDTO, GraficoPizzaDTO,
} from 'src/types';
import { useToast, ToastContainer } from 'src/hooks/useToast';
import { fCurrency, fNumber } from 'src/utils/format-number'; export default function DashboardView() { const { toasts, showError, removeToast } = useToast(); const [dashboard, setDashboard] = useState(null); const [loading, setLoading] = useState(true); useEffect(() => { const fetchDashboard = async () => { try { setLoading(true); const data = await dashboardService.getDashboardCompleto(); setDashboard(data); } catch (error) { const message = error.response?.data?.message || 'Erro ao carregar dashboard'; showError(message); } finally { setLoading(false); } }; fetchDashboard(); }, [showError]); if (loading) { return (); } if (!dashboard) { return ( Erro ao carregar o dashboard. Tente novamente. ); } const { kpis, saldoCaixa, entradasMes, saidasMes, alertas, contagemEvento, evolucaoCaixa, despesasPorCategoria, receitasPorTipo } = dashboard; // Preparar dados para gráfico de evolução de caixa const evoluacaoCaixaData = { series[ { name'Saldo', data((d) => d.valor), }, ], categories((d) => d.data), }; // Preparar dados para gráfico de despesas por categoria const despesasData = { series((d) => d.valor), labels((d) => d.label), }; // Preparar dados para gráfico de receitas por tipo const receitasData = { series((d) => d.valor), labels((d) => d.label), }; return ( Dashboard | Ticomia Financeiro</title> Dashboard Visão geral do evento e métricas financeiras {/* Alertas críticos */} {alertas.pagamentosUrgentes.length > 0 && ( ⚠️ {alertas.pagamentosUrgentes.length} pagamento(s) vencedo(s) ou próximo de vencer! )} {/* Cards de KPIs principais */} = 0 ? 'warning' 'success'} /> {/* Informações do evento */} {contagemEvento && ()} {/* Grid principal com gráficos e tabelas */} {/* Evolução de caixa */} Evolução do Saldo {/* KPIs secundários */} {/* Gráficos de Receitas e Despesas */} Receitas por Tipo Despesas por Categoria {/* Top Vendedores */} Top 10 Vendedores # Nome</TableCell> Ingressos</TableCell> Faturamento</TableCell> Comissão</TableCell> Ticket Médio</TableCell> {kpis.top10Vendedores.map((vendedor, index) => ( {vendedor.nome} {fNumber(vendedor.totalIngressosVendidos)} {fCurrency(vendedor.totalFaturamento)} {fCurrency(vendedor.valorComissao)} {fCurrency(vendedor.ticketMedio)} ))} {/* Equipamentos */} );
} function KPICard({ title, value, subvalue, icon, color = 'primary', sx }) { return ( {title} {value} {subvalue && ( {subvalue} )} {icon && ()} );
} function EventoCard({ evento, sx }) { const dias = evento.diasRestantes; return ( {evento.nomeEvento} {evento.dataEvento} {dias} dias restantes {evento.semanasRestantes}s</Typography> semanas );
}
